### ISSUE TITLE
Link to lhcbqa.web.cern.ch/ 

### ISSUE THREAD

**Issue by KonstantinSchubert** [lhcb/starterkit#21]
This is a proposal inform students about the existence of https://lhcbqa.web.cern.ch/ somewhere in the lessons.

If you have a suggestion where to add it, I can make a pull request.

**Comment by apuignav** [comment]
Honestly, I'm a bit hesitant in adding this in the lessons, since it's not
officially sanctioned. While I like the idea very much, right now it's just
adding more noise to the already complicated world of finding useful
information, since it doesn't duplicate information on the twiki. In a
sense, the way things are right now it's still more useful to complete the
twiki, as much as I hate it.

Either this becomes something more official and as unique as possible or I
would leave it out of the lessons. Too much confusion.

Albert

**Comment by KonstantinSchubert** [comment]
Okay, I understand. Really.
I like how well-structured the lessons are and I would hate to be the one who starts cluttering them.

**Comment by alexpearce** [comment]
It is hard getting something new off the ground. Without momentum, there's a danger that any Q&As that are made are lost because people don't use the service, but on the other hand it could become an excellent resource.

The [getting help lesson](https://lhcb.github.io/first-analysis-steps/14-asking-questions.html) would be a good place to put a link I think.

**Comment by KonstantinSchubert** [comment]
I have thought about this for a bit.

I completely agree with @apuignav  that the starterkit should not recommend https://lhcbqa.web.cern.ch/lhcbqa/ above the twiki as a source of information. 

However, almost all questions posted on lhcbqa have been answered within a couple of days. This means, in my opinion, that lhcbqa already provides a tangible benefit to the user, even if it is not (yet?) officially sanctioned.
Maybe this is an argument to at least include a link to it in the [getting help lesson](https://lhcb.github.io/first-analysis-steps/14-asking-questions.html), as proposed by Alex? Maybe with a disclaimer that it is experimental?

**Comment by apuignav** [comment]
I like it in the getting help lesson.

On Wed, Jun 1, 2016 at 3:09 PM, Konstantin Schubert <
notifications@github.com> wrote:

> I have thought about this for a bit.
> 
> I completely agree with @apuignav https://github.com/apuignav that the
> starterkit should not recommend https://lhcbqa.web.cern.ch/lhcbqa/ above
> the twiki as a source of information.
> 
> However, almost all questions posted on lhcbqa have been answered within a
> couple of days. This means, in my opinion, that lhcbqa already provides a
> tangible benefit to the user, even if it is not (yet?) officially
> sanctioned.
> Maybe this is an argument to at least include a link to it in the getting
> help lesson
> https://lhcb.github.io/first-analysis-steps/14-asking-questions.html,
> as proposed by Alex? Maybe with a disclaimer that it is experimental?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/lhcb/starterkit/issues/21#issuecomment-222986814, or mute
> the thread
> https://github.com/notifications/unsubscribe/AAqA8PmjdNgTx59UNogPfFuW-M0CUXhjks5qHYR_gaJpZM4IiskN
> .

## 

Dr. Albert Puig Navarro
Laboratoire de Physique des Hautes Energies
Ecole Polytechnique Fédérale de Lausanne (EPFL)
BSP 614.4 (Cubotron UNIL) CH-1015 Lausanne
EPFL Phone: 021 6939808
CERN Phone: 72518

**Comment by kdungs** [comment]
This seems to be resolved by https://github.com/lhcb/first-analysis-steps/issues/170.
